### ISSUE TITLE
gamma_2 seems to have the wrong sign

### ISSUE THREAD

**Issue by kostrzewa** [maowerner/sLapH-contractions#41]
The gamma basis should be consistent with the Dirac basis defined in the tmLQCD documentation, as used in the [Dirac operator](https://github.com/etmc/tmLQCD/blob/master/operator/D_psi_body.c) operator or the [gamma macros](https://github.com/etmc/tmLQCD/blob/master/su3spinor.h)

**Comment by chelmes** [comment]
I checked that and it seems to be an overall minus sign in the whole basis. Should I correct for that?

**Comment by kostrzewa** [comment]
There is only a minus sign in gamma_2, @martin-ueding , @maowerner  and I went through all of the gammas. I believe that @maowerner  already corrected gamma_2, but I might be wrong.

**Comment by chelmes** [comment]
I corrected gamma2 in branch derivative-opreators and will implement a unit test now.=

**Comment by chelmes** [comment]
Unit Tests for gamma matrices in place. Now using gamma matrices as in <a href="https://github.com/etmc/tmLQCD/blob/master/su3spinor.h">gamma macros</a>.
