### ISSUE TITLE
Run googletest tests on Travis CI

### ISSUE THREAD

**Issue by martin-ueding** [maowerner/sLapH-contractions#43]
The code only compiles the googletest based tests when the gtest framework can be found. On Travis CI, the needed Ubuntu packages are installed, but for some reason it is not picked up correctly.

On my Fedora laptop, the tests are always build and run, so in general this seems to work.

Make sure that they are also build on Travis CI.

**Comment by maowerner** [comment]
https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/

It seems we need to build gtest from source on debian systems

**Comment by martin-ueding** [comment]
This seems a bit strange, but oh well. Now it works on Travis CI. Thanks!
